### ISSUE TITLE
Uncaught TypeError: (0 , _hashIt2.default) is not a function

### ISSUE THREAD

**Issue by dcowan-e-courier** [CacheControl/json-rules-engine#344]
When calling run getting this error.  This is implementing the simple first example provided in the documentation in a react web app

fact.js:119 Uncaught TypeError: (0 , _hashIt2.default) is not a function
    at Function.hashFromObject (fact.js:119:1)
    at Fact.getCacheKey (fact.js:112:1)
    at Almanac._setFactValue (almanac.js:149:1)
    at Almanac._addConstantFact (almanac.js:136:1)
    at new Almanac (almanac.js:63:1)
    at Engine.run (engine.js:377:1)

**Comment by chris-pardy** [comment]
@dcowan-e-courier can you check which version of `hash-it` you have installed?

**Comment by siawyoung** [comment]
I'm seeing this error too. If it helps, I have the same code running successfully in a Node environment, but running it in a browser environment (Chrome) produces the above error. The exact version of hash-it on both environments:

```
hash-it@^6.0.0:
  version "6.0.0"
  resolved "https://registry.yarnpkg.com/hash-it/-/hash-it-6.0.0.tgz#188df5a8ca2f8e036690e35f2ef88bd9417ff334"
  integrity sha512-KHzmSFx1KwyMPw0kXeeUD752q/Kfbzhy6dAZrjXV9kAIXGqzGvv8vhkUqj+2MGZldTo0IBpw6v7iWE7uxsvH0w==
```

**Comment by chris-pardy** [comment]
@siawyoung @dcowan-e-courier  this does seem to be related to the export mapping on the `hash-it` package and how something like webpack is resolving that.

**Comment by MohHamoud** [comment]
I am having the same error in an existing project, I reproduced the issue by creating a project using create-react-app as @siawyoung mentioned, is there a fast way to fix it? 
I understand that create-next-app creates a next.js application, which I don't prefer doing.

**Comment by MohHamoud** [comment]
@chris-pardy I cloned the project, then copied the src files and "yarn add"-ed the required dependencies
it worked fine, without specifying the version of the hash-it nor the webpack

**Comment by chris-pardy** [comment]
@MohHamoud this makes sense since we transform the source from modules to common / require. As part of that babel is doing a default import transformation. Then the webpack resolution is giving us the wrong version of the hash-it library.
