### ISSUE TITLE
Can't Import Engine

### ISSUE THREAD

**Issue by junglejf** [CacheControl/json-rules-engine#78]
Im getting this error:

Debugging with inspector protocol because Node.js v9.3.0 was detected.
node --inspect-brk=32430 advanced-example.js 
Debugger listening on ws://127.0.0.1:32430/b7f8b347-8423-4f78-881a-d57242f4279d
Debugger attached.
/home/felipe/Downloads/TestRules/advanced-example.js:1
(function (exports, require, module, __filename, __dirname) { import { Engine } from 'json-rules-engine'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
Waiting for the debugger to disconnect...
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

**Comment by CacheControl** [comment]
@junglejf looks like you are trying to use ESModule syntax in Node.js.  Node.js does not yet support that syntax.  You will need to either import the engine using `require()`, or use a transpiler/shim such as babel or [esm](https://github.com/standard-things/esm).
